name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # 3. Télécharger ecs-cli et rendre exécutable
      - name: Install ecs-cli
        run: |
          # Télécharger ecs-cli binaire Linux directement
          curl -Lo ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          chmod +x ecs-cli
          sudo mv ecs-cli /usr/local/bin/

      # Vérification de l'installation de ecs-cli
      - name: Verify ecs-cli installation
        run: |
          ecs-cli --version

      # 4. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t cats-back .

      # 5. Se connecter à ECR et pousser l'image Docker
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084828604086.dkr.ecr.eu-north-1.amazonaws.com
          docker tag cats-back:latest 084828604086.dkr.ecr.eu-north-1.amazonaws.com/cats/back:latest
          docker push 084828604086.dkr.ecr.eu-north-1.amazonaws.com/cats/back:latest

      # 6. Mettre à jour ECS
      - name: Update ECS Service
        run: |
          ecs-cli compose --file docker-compose.yml --project-name cats-back --cluster BackCatsCluster service up


