name: Deploy to AWS

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'un push est effectué sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le workflow

    steps:
      # 1. Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Remplacez avec votre région AWS

      # 3. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t back_cats-app .

      # 4. Se connecter à ECR et pousser l'image Docker
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084828604086.dkr.ecr.eu-north-1.amazonaws.com
          docker tag your-image-name:latest 084828604086.dkr.ecr.eu-north-1.amazonaws.com/your-repo-name:latest
          docker push 084828604086.dkr.ecr.eu-north-1.amazonaws.com/your-repo-name:latest

      # 5. Mettre à jour ECS ou Elastic Beanstalk (selon votre configuration)
      - name: Update ECS Service
        run: |
          ecs-cli compose --file docker-compose.yml --project-name your-project-name service up
